spring.application.name=abac-access-control

# MyBatis 基础配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.xie.platform.model
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-handlers-package=com.xie.platform.config

# MySQL 业务库配置
spring.datasource.url=jdbc:mysql://localhost:3306/abac_control?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=w86#qNwV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT 登录态配置
security.jwt.secret=abac-secret-key-which-is-long-enough-32bytes
security.jwt.expire=7200000

# Spring Boot Multipart 上传大小限制
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MinIO 对象存储配置
# enabled=true 后，文件中心会把真实文件上传到 MinIO，而不是只手工保存外部地址
storage.minio.enabled=true
# 注意这里必须使用 S3 API 端口 9000，不能使用 Console 的 9001
storage.minio.endpoint=http://localhost:9000
# 这里使用你当前 Docker 容器里配置的 MINIO_ROOT_USER / MINIO_ROOT_PASSWORD
storage.minio.access-key=admin
storage.minio.secret-key=12345678
# 这里是项目默认使用的 bucket 名；如果你在 Console 里创建的不是这个名字，请同步改成实际 bucket
storage.minio.bucket=abac
# 下载时由后端生成 MinIO 临时链接，15 分钟后失效
storage.minio.download-expiry-minutes=15
# 本地开发环境允许后端在 bucket 不存在时自动创建
storage.minio.auto-create-bucket=true
